server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5433/expert
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true